### ISSUE TITLE
Parcelable with generic type not generated into a nav argument

### ISSUE THREAD

**Issue by marosseleng** [raamcosta/compose-destinations#530]
Hello! I came across what I believe is a bug:

I have a generic `data class` for modeling basic screen states ((re)loading, loaded, error, etc.) that looks as follows:

```kotlin
@Parcelize
internal data class OperationStatus<ResultT : Parcelable>(
    val isLoading: Boolean = false,
    val result: ResultT? = null,
    val error: Exception? = null,
) : Parcelable
```
then I have my destination:
```kotlin
@Destination
@Composable
internal fun ExampleScreen(
    navigator: DestinationsNavigator,
    status: OperationStatus<SomeParcelableClass>,
)
```

The problem is that the generated `ExampleScreenDestination` does not have an `invoke` override, with `status: OperationStatus<SomeParcelableClass>` as a parameter.

Is this a bug or is there any limitation, why this isn't possible? According to docs, `Parcelable` can be used as navigation argument, but maybe I am missing something.

I am aware of possible solution introduced in #29 (to box my type in another class), but I find that a bit cumbersome.

Also, regarding separate boxed argument class, I found another bug: Let's say I create a class
```kotlin
@Parcelize
internal data class MyBoxedStatusArg(val status: OperationStatus<SomeParcelableClass>)
```
and add it as an argument to my Destination:
```kotlin
@Destination
@Composable
internal fun ExampleScreen(
    navigator: DestinationsNavigator,
    status: MyBoxedStatusArg,
)
```
I then get a compilation error that the created **public** subclass exposes its internal supertype (I believe it is because of its definition):
```kotlin
public class MyBoxedStatusArgNavType(
    private val stringSerializer: DestinationsNavTypeSerializer<Parcelable>
) : DestinationsNavType<MyBoxedStatusArg?>()
```
Would it be possible to make the generated `ArgNavType` to respect the "argument's" visibility?

Thank you for reply!

**Comment by raamcosta** [comment]
> Would it be possible to make the generated ArgNavType to respect the "argument's" visibility?

I believe this has been fixed recently.

Parcelable with type arguments are not currently supported, no. The only type arguments we support are the ones inside Array and ArrayList.
I'll mark this as possible future enhancement. Thank you!
