### ISSUE TITLE
Nullable String navigation parameter with newline characters crashes

### ISSUE THREAD

**Issue by Olaleo** [raamcosta/compose-destinations#85]
When navigation to a Destination with a nullable String navigation parameter

```
@Destination()
@Composable
fun SecondScreen(string: String?) {
    Surface(
        modifier = Modifier.fillMaxSize(),
        color = MaterialTheme.colors.background
    ) {
        Greeting(string?:"Null string")
    }
}
```

with a String that contains newline characters 
```
@Destination(start = true)
@Composable
fun StartScreen(navigator: DestinationsNavigator) {
    Surface(
        modifier = Modifier.fillMaxSize(),
        color = MaterialTheme.colors.background
    ) {
        Column(modifier = Modifier) {
            Greeting("Start")
            Button(onClick = { navigator.navigate(SecondScreenDestination("Test\r\nTest")) }) {
                Text(text = "Navigate")
            }
        }
    }
}
```

The nav controller crashes with the following stacktrace

```
2022-04-04 14:33:31.010 28988-28988/com.example.composetest E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.composetest, PID: 28988
    java.lang.IllegalArgumentException: Navigation destination that matches request NavDeepLinkRequest{ uri=android-app://androidx.navigation/second_screen?string=Test%0D%0ATest } cannot be found in the navigation graph NavGraph(0x78dcd1ef) route=root startDestination={Destination(0x10599af6) route=start_screen}
        at androidx.navigation.NavController.navigate(NavController.kt:1660)
        at androidx.navigation.NavController.navigate(NavController.kt:1980)
        at androidx.navigation.NavController.navigate$default(NavController.kt:1975)
        at androidx.navigation.NavController.navigate(NavController.kt:1961)
        at com.ramcosta.composedestinations.navigation.DestinationsNavController.navigate(DestinationsNavController.kt:27)
        at com.ramcosta.composedestinations.navigation.DestinationsNavigator$DefaultImpls.navigate(DestinationsNavigator.kt:59)
        at com.ramcosta.composedestinations.navigation.DestinationsNavController.navigate(DestinationsNavController.kt:13)
        at com.ramcosta.composedestinations.navigation.DestinationsNavigator$DefaultImpls.navigate$default(DestinationsNavigator.kt:54)
        at com.example.composetest.MainActivityKt$StartScreen$1$1$1.invoke(MainActivity.kt:44)
        at com.example.composetest.MainActivityKt$StartScreen$1$1$1.invoke(MainActivity.kt:44)
        at androidx.compose.foundation.ClickableKt$clickable$4$gesture$1$2.invoke-k-4lQ0M(Clickable.kt:153)
        at androidx.compose.foundation.ClickableKt$clickable$4$gesture$1$2.invoke(Clickable.kt:142)
        at androidx.compose.foundation.gestures.TapGestureDetectorKt$detectTapAndPress$2$1$1.invokeSuspend(TapGestureDetector.kt:223)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:178)
        at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:166)
        at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:431)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:420)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:328)
        at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter$PointerEventHandlerCoroutine.offerPointerEvent(SuspendingPointerInputFilter.kt:511)
        at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter.dispatchPointerEvent(SuspendingPointerInputFilter.kt:406)
        at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter.onPointerEvent-H0pRuoY(SuspendingPointerInputFilter.kt:419)
        at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:310)
        at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:297)
        at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:297)
        at androidx.compose.ui.input.pointer.NodeParent.dispatchMainEventPass(HitPathTracker.kt:179)
        at androidx.compose.ui.input.pointer.HitPathTracker.dispatchChanges(HitPathTracker.kt:98)
        at androidx.compose.ui.input.pointer.PointerInputEventProcessor.process-BIzXfog(PointerInputEventProcessor.kt:80)
        at androidx.compose.ui.platform.AndroidComposeView.sendMotionEvent-8iAsVTc(AndroidComposeView.android.kt:1159)
        at androidx.compose.ui.platform.AndroidComposeView.handleMotionEvent-8iAsVTc(AndroidComposeView.android.kt:1109)
        at androidx.compose.ui.platform.AndroidComposeView.dispatchTouchEvent(AndroidComposeView.android.kt:1059)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3143)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2814)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3143)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2814)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3143)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2814)
2022-04-04 14:33:31.011 28988-28988/com.example.composetest E/AndroidRuntime:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3143)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2814)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:517)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1894)
        at android.app.Activity.dispatchTouchEvent(Activity.java:4131)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:475)
        at android.view.View.dispatchPointerEvent(View.java:14648)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6531)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6302)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5768)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5825)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5791)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5943)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5799)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6000)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5772)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5825)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5791)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5799)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5772)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8672)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8623)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8521)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8795)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:231)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:335)
        at android.os.Looper.loop(Looper.java:183)
        at android.app.ActivityThread.main(ActivityThread.java:8068)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
```

**Comment by raamcosta** [comment]
Hi @Olaleo!

Really? Super interesting 🤔
I’ll check this out in a couple of hours and keep my findings here. This specific case I have never tried before, so thank you for reporting!

**Comment by raamcosta** [comment]
So after some time of me figuring out a workaround for this, it seems like this was already fixed in Official Jetpack Compose Navigation:
https://issuetracker.google.com/issues/217815060?hl=pt-br

It will be coming on the next stable release 2.4.2. 
At the moment the library uses 2.4.1 which is the last stable release we have now.
So this will be fixed for Compose Destinations too once 2.4.2 comes out 🙂 

Is this blocking you or are you ok to wait for the official fix?

**Comment by Olaleo** [comment]
I am ok to wait for the official fix, as I have a work around for it

**Comment by raamcosta** [comment]
This should be fixed on version 1.4.3, I tested on my side and it worked! 🎉 

Let me know if it fixes it for you too!

**Comment by Olaleo** [comment]
After upgrading to 1.4.3-beta the project does not compile as the generated ```TypedDestination``` objects does not implement the
```operator fun invoke(navArgs: T): Direction``` function from ```DestinationSpec```.

**Comment by raamcosta** [comment]
Holy **** 🤦 

If you are seeing that error then the only possible explanation is that I built the version for maven with not commit stuff I was playing around with.
I will fix it right away, give it half an hour or so and it should be 1.4.4-beta on maven central.

**Comment by raamcosta** [comment]
@Olaleo 1.4.4-beta available with the build fix!

Sorry for the inconvenience! 😕 
And thank you for letting me know! 🙇

**Comment by Olaleo** [comment]
This also works on my side now.

**Comment by raamcosta** [comment]
Great! Thanks once again 🙏
