### PR TITLE
Version catalogs for `compose-1.2`

### PR DESCRIPTION
**Pull request by imashnake0**
Removed the `buildSrc` module [in favour](https://twitter.com/JakeWharton/status/1491052851887755266?s=20&t=lvVbE1f9lEhYPYqaO0FIFg) of [version catalogs](https://docs.gradle.org/current/userguide/platforms.html).

**Summary of changes:**
1. Created the `libs` catalog: `gradle/libs.versions.toml`.
2. Migrated all build files.
3. Purged `buildSrc`.
4. Made `when` exhaustive, this led to a compilation error :thinking:.

### CODE REVIEW

**Review by imashnake0 — COMMENTED** [review]
Interestingly I get this error only after my changes:
```
'when' expression must be exhaustive, add necessary 'ProfileSettingsScreenDestination' branch or 'else' branch instead
```
Shouldn't be a deal-breaker though.

**Comment by raamcosta** [comment]
> Interestingly I get this error only after my changes:
> 
> ```
> 'when' expression must be exhaustive, add necessary 'ProfileSettingsScreenDestination' branch or 'else' branch instead
> ```
> 
> Shouldn't be a deal-breaker though.

Try a clean build. KSP and Kotlin compiler sometimes give that error for no reason 😐

**Comment by imashnake0** [comment]
> Try a clean build. KSP and Kotlin compiler sometimes give that error for no reason :neutral_face:

Did a clean build on the original `compose-1.2` branch and got the same error, doesn't seem to have anything to do with my changes. Let me know if and how you want me to fix it, I can revert the commit too if needed.

File: playground/src/main/java/com/ramcosta/samples/playground/commons/DestinationsAppExtensions.kt [hunk 1]
```diff
@@ -33,6 +33,8 @@ fun DirectionDestination.DrawerContent(
         GoToProfileConfirmationDestination,
         SettingsScreenDestination,
         ThemeSettingsDestination -> Unit
```
Comment (imashnake0) [inline playground/src/main/java/com/ramcosta/samples/playground/commons/DestinationsAppExtensions.kt:35]:
```suggestion
        ThemeSettingsDestination,
        ProfileSettingsScreenDestination -> Unit
```

File: playground/src/main/java/com/ramcosta/samples/playground/commons/DestinationsAppExtensions.kt [hunk 2]
```diff
@@ -33,6 +33,8 @@ fun DirectionDestination.DrawerContent(
...
+
+        else -> { TODO() }
```
Comment (imashnake0) [inline playground/src/main/java/com/ramcosta/samples/playground/commons/DestinationsAppExtensions.kt:37]:
```suggestion

```

File: playground/src/main/java/com/ramcosta/samples/playground/commons/DestinationsAppExtensions.kt (hunk 1 above)
Comment (raamcosta) [reply playground/src/main/java/com/ramcosta/samples/playground/commons/DestinationsAppExtensions.kt:35]: Yeah go with this then. Maybe this is indeed something I messed up while merging the last time 😁
Since it’s only on the sample app, it’s totally possible I didn’t ran it 🙂

Comment (raamcosta) [reply playground/src/main/java/com/ramcosta/samples/playground/commons/DestinationsAppExtensions.kt:35]: Sorry for the confusion!

Comment (imashnake0) [reply playground/src/main/java/com/ramcosta/samples/playground/commons/DestinationsAppExtensions.kt:35]: No worries!

**Comment by imashnake0** [comment]
@raamcosta Done!

**Comment by raamcosta** [comment]
Thanks! 🙇
